[package]
name = "vim-buffer"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = { version = "0.29.0", default-features = false, features = [
  "events",
] }

[dev-dependencies]
color-eyre = "0.6.5"
