allowed-idents-below-min-chars = []
allow-expect-in-consts = false
allow-expect-in-tests = true
allow-indexing-slicing-in-tests = true
allow-mixed-uninlined-format-args = false
allow-panic-in-tests = true
allow-renamed-params-for = []
allow-unwrap-in-consts = false
allow-unwrap-in-tests = true
avoid-breaking-exported-api = false
check-incompatible-msrv-in-tests = true
check-inconsistent-struct-field-initializers = true
check-private-items = true
disallowed-names = []
enum-variant-name-threshold = 1
excessive-nesting-threshold = 4
lint-commented-code = true
max-suggested-slice-pattern-length = 20
max-trait-bounds = 1
standard-macro-braces = [{ name = "actions", brace = "[" }]
too-many-arguments-threshold = 4
too-many-lines-threshold = 50
type-complexity-threshold = 100
