[files]
extend-exclude = [".git", "rustfmt.toml", "LICENSE-*", "tests/keys.rs"]
ignore-hidden = false
ignore-files = false
ignore-dot = false
ignore-vcs = true
ignore-global = false
ignore-parent = false

[default]
binary = false
check-filename = true
check-file = true
unicode = true
locale = "en-gb"
extend-ignore-re = [
  "(?m)^.*// ignore-spell$",
  ".*buffer\\.update_from_string\\(\".*\"\\)",
]

[default.extend-identifiers]
CARGO_TERM_COLOR = "CARGO_TERM_COLOR"
