name: Coverage

on: [pull_request, push]

env:
    CARGO_TERM_COLOR: always

jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                toolchain: nightly
                override: true

            - name: Install cargo-binstall
              uses: cargo-bins/cargo-binstall@main

            - name: Install tarpaulin
              run: cargo binstall -y cargo-tarpaulin

            - name: Check coverage
              run: cargo tarpaulin --doc --tests --fail-under 100
