name: Rustdoc

on:
  push:
    paths:
      - '**/*.rs'
      - 'README.md'
      - '.github/workflows/rustdoc.yml'
  pull_request:
    paths:
      - '**/*.rs'
      - 'README.md'
      - '.github/workflows/rustdoc.yml'

env:
    CARGO_TERM_COLOR: always

jobs:
    doc:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            rust: [stable, nightly]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Restore target
              uses: actions/cache@v5
              with:
                path: |
                  target
                  ~/.cargo
                key: doc-target-${{ matrix.rust }}
                restore-keys: doc-target-${{ matrix.rust }}

            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                toolchain: ${{ matrix.rust }}
                override: true

            - name: Check documentation
              run: RUSTDOCFLAGS="-D warnings" cargo doc --document-private-items --all --release
