name: Typos

on: [pull_request, push]

env:
  CLICOLOR: 1

jobs:
  typos:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v4

    - name: Spell Check Repo
      uses: crate-ci/typos@v1.38.1
