name: Taplo

on: [pull_request, push]

jobs:
    taplo:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                toolchain: stable
                override: true

            - name: Install cargo-binstall
              uses: cargo-bins/cargo-binstall@main

            - name: Install taplo
              run: cargo binstall -y taplo-cli

            - name: Check formatting
              run: taplo format --check
